script/test: run tests both with sync and async storage

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -19,7 +19,19 @@ function do_license_check()
 
 function do_test()
 {
-    bundle_exec rake "$@"
+    case $1 in
+    sync)
+        echo "Running tests using the sync Redis driver"
+        CONFIG_REDIS_ASYNC=false bundle_exec rake
+        ;;
+    async)
+        echo "Running tests using the async Redis driver"
+        CONFIG_REDIS_ASYNC=true bundle_exec rake
+        ;;
+    *)
+      echo "Invalid Redis driver option: $1"
+      exit 1
+    esac
 }
 
 function run_tests()
@@ -32,7 +44,7 @@ function run_tests()
 
     export RACK_ENV=test
 
-    do_license_check && do_test
+    do_license_check && do_test "sync" && do_test "async"
 }
 
 trap 'cleanup' INT
